[workspace]
resolver = "2"
members = ["rusl", "tiny-cli", "tiny-start", "tiny-std"]
exclude = ["test-runners/alloc-st-main", "test-runners/no-alloc-main", "test-runners/threaded-main", "test-runners/test-lib"]

