name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  CI: true

jobs:
  lint:
    # Want to run this on aarch64 but https://github.com/actions/runner-images/issues/5631
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
          components: clippy
      - name: Check formatting
        run: ./.github/fmt.sh
      - name: Check clippy
        run: ./.github/clippy.sh
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-gnu
      - name: Run tests
        run: ./.github/test.sh
      - name: Run test runners
        run: ./.github/runners.sh
